volumes:
  overpass-db:

version: '3.8'
services:
  overpass:
    # specify the image here
    image: wiktorn/overpass-api:latest
    container_name: overpass
    # uncomment if you want to build the image yourself
    build: .
    ports:
      - 12345:80
    volumes:
      # use a docker managed volume
      - overpass-db:/db
    environment:
      - OVERPASS_META=no
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/germany/berlin-latest.osm.bz2
      - OVERPASS_DIFF_URL=https://download.geofabrik.de/europe/germany/berlin-updates/
      - OVERPASS_UPDATE_SLEEP=3600
      - OVERPASS_USE_AREAS=false
    healthcheck:
      test: ["CMD-SHELL", "curl --noproxy '*' -qf 'http://localhost/api/interpreter?data=\\[out:json\\];node(1);out;' | jq '.generator' |grep -q Overpass || exit 1"]
      start_period: 48h
